# This file was generated by GoReleaser. DO NOT EDIT.
cask "kitt" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "058117e614ccdbe7a8f497e9b9818e0491066ac9848c0b8c2e2e6ed771dda104"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff60763cdc13ba8492bf1a267e53aa95560f2e47c0c9644dc58f281c08bb526f"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "64deaa01bef638befe0e497b81970a76e201962df7d5c8c0c9c7bf2498c9a511"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d2a8f03da60ae44192579b467bb0fb5fd1c09250001dc9f9460b31187f45d818"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kitt"
  desc "Install, pin and publish AI agent skills per project, straight from git."
  homepage "https://github.com/anthony-cordani/kitt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kitt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kitt"]
    end
  end

  # No zap stanza required
end
