# This file was generated by GoReleaser. DO NOT EDIT.
cask "kitt" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "f394003299da36b2d42f44ebdc94c9b68fc95f300b9eecc78c808b204120a678"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2d1b69768f5f9e55b7483f0ff1fa1336e2b618cc0840470e9a2adbad9bc0d3f4"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d98432da8d95da0ac0daac4544b2abc81c275e6075550d12162136641f0d393e"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1c4b34b28d154a9723aec798988d03b13456d686f0bc88a666a4677646a7d90c"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kitt"
  desc "Install, pin and publish AI agent skills per project, straight from git."
  homepage "https://github.com/anthony-cordani/kitt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kitt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kitt"]
    end
  end

  # No zap stanza required
end
