# This file was generated by GoReleaser. DO NOT EDIT.
cask "kitt" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "41ef1ac9ceb74cc6f67f8190fae5e72a3e0a7c0fdbfe42e92536be249e5daf87"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "40200f5cc1ff089a72de4bef78957f126db90e6efbe63213236645a65903350b"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "62709913cbe8c11baae85699bc81c2f39a0638a7bbd82e49f154e459433079ec"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ced03ac09e40880b7e20b0ff37a44f9eaa7dbdc16c98265aa57e36b62fa48137"
      url "https://github.com/anthony-cordani/kitt/releases/download/v#{version}/kitt_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kitt"
  desc "Install, pin and publish AI agent skills per project, straight from git."
  homepage "https://github.com/anthony-cordani/kitt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kitt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kitt"]
    end
  end

  # No zap stanza required
end
